### ISSUE TITLE
Data::Printer filters ignore inheritance

### ISSUE THREAD

**Issue by Ovid** [garu/Data-Printer#115]
Though I'm not a fan of inheritance, I'm sometimes stuck with it. With `Data::Printer`, it would be very convenient, particularly when working with large OO codebases, if the `filters` recognized blessed objects and respected inheritance.

Here's an example:

```perl
#!/usr/bin/env perl

use 5.012;
use warnings;
use Data::Printer filters => {
    Mammal => sub { $_[0]->name },
};

{
    package Mammal;

    sub new {
        my ( $class, $arg_for ) = @_;
        return bless $arg_for => $class;
    }

    sub name { $_[0]->{name} }
}
{
    package Dog;
    our @ISA = 'Mammal';

    sub bark { say "Woof!" }
}

my $mammal = Mammal->new( { name => 'Billy' } );
my $dog = Dog->new( { name => 'Spot' } );
say $dog->isa('Mammal') ? "Yes, dog is a mammal" : "No, dog is not a mammal";
p $mammal;
p $dog;
```

That prints:

```
Yes, dog is a mammal
Billy
Dog  {
    Parents       Mammal
    public methods (1) : bark
    private methods (0)
    internals: {
        name   "Spot"
    }
}
```

This means when I am working on a huge code based in Catalyst, and my `Project::Schema::Result::Customer` class gets subclassed as `Project::Model::DB::Customer`, I have to create the same filter for each of them. It's rather frustrating, particularly when I have hundreds of such classes.

I've switched to using the `-class` key as a workaround.

**Comment by KES777** [comment]
How about `_data_printer`?
```
sub Mammal::_data_printer {
    $_[0]->name
}
```

**Comment by KES777** [comment]
@garu Would it be OK if `DDP` add `_data_printer` method automatically to the specified class:

For example in case:
```
use Data::Printer filters => {
    Mammal => sub { $_[0]->name },
};
```
add `_data_printer` (maybe _DATA_PRINTER, to denote method which is called automatically, like perl does for other methods: DESTROY, FETCH, etc) to `Mammal` class

**Comment by Ovid** [comment]
I would be uncomfortable with the name beginning with an underscore because that implies a private method that we should not touch. If it were publicly exposed and documented as a part of the class's contract, that would be great.

**Comment by dur-randir** [comment]
@Ovid, but it is, in the section "MAKING YOUR CLASSES DDP-AWARE (WITHOUT ADDING ANY DEPS)". This requires a change of how you set up filters, but if you don't like _data_printer name, you can change it to anything in the config.

**Comment by KES777** [comment]
@Ovid Without underscore and with all uppercase letters it may conflict with future reserved word
>Subroutines whose names are in all upper case are reserved to the Perl core, as are modules whose names are in all lower case. A subroutine in all capitals is a loosely-held convention meaning it will be called indirectly by the run-time system itself, usually due to a triggered event.

**Comment by garu** [comment]
Hi @Ovid, thanks for the report, and apologies for not replying to this sooner. Also, many thanks to @KES777 and @dur-randir for offering detailed help and potential workarounds!

So, triggering filters only on exact matches is by design, but maybe it's the wrong way to approach things. In fact, Data::Printer comes with a [Filter::DB](https://github.com/garu/Data-Printer/blob/master/lib/Data/Printer/Filter/DB.pm#L70) that, much like your filter, is a "-class" block with an `->isa()` check for DBIC::Result children. The original concept was that you would probably only want an object filter on an exact match, otherwise you would explicitly say "hey, if it's a class that inherits from X, do this", and the code would reflect that decision.

However, this delegates the responsibility of what to print to the original class author, not to whomever is subclassing (and debugging) it. And since subclassing means (at least in theory) that you would behave in a similar fashion, it makes sense to check whether anything on the inheritance tree can be pretty-printed.

The only question remaining is: what if the class has two parents and they both have DDP filters? Show both? Use the ISA order from `mro::get_linear_isa`? Do something else entirely? What if we create an option for this as well, what should we call it and what would be the available options to chose from?

I'd love to hear what you all think!

**Comment by garu** [comment]
Similar to #42

**Comment by garu** [comment]
Good news, everyone! Version 1.0 (on github master, soon on CPAN as 0.99_002) fixes the issue by changing the behaviour of filters to:

1. class has a filter? Use it.
2. traverse entire linear ISA checking for filters (or stringification) in each parent class. You may disable this step by using `class => { parent_filters => 0 }` (defaults to 1)
3. Let all "-class" filters have a go
4. Use the generic object filter, which:
    4.1. first checks for a `_dataprinter` sub and uses it if available.
    4.2. then checks for stringification (including inherited stringification) and uses if available (disable this step with `class => { stringify => 0 }`)
    4.3. then print the standard class dump.

I hope this is a satisfactory solution. If you have any comments or concerns, now is the time - or at least until 1.0 reaches CPAN :)
