### ISSUE TITLE
Cannot use a symlink for config file

### ISSUE THREAD

**Issue by barefootcoder** [garu/Data-Printer#151]
Pretty much exactly what the issue title states.  The error I get is: `*** WARNING *** rc file '/home/vagrant/.dataprinter' doesn't look like a plain file. Skipping.`  And of course the offending line of code is:
```
    if ( -l $file || (!-f _) || -p _ || -S _ || -b _ || -c _ ) {
```

So I guess you're _explicitly_ not allowing it to be a symlink ... ? :shrug: I'm just not sure why.  It would really be convenient for me if I could store this file in my repo where I keep all my `.rc` files and symlink it to the name Data::Printer is looking for, which is how I handle all my other config files.  Any particular reason using a symlink is disallowed?

**Comment by garu** [comment]
Hi! Thank you for using Data::Printer and for taking the time to file this issue.

You're right, it explicitly doesn't allow symlinks. This is because the .dataprinter file is `eval()`d into the running process, which may have elevated privileges and, even if it doesn't, Perl being Perl, it could (potentially) fiddle with the entire process. So we try our best to raise the security of the file before doing it, including making sure it's an actual file, not a symlink, a socket or a named pipe, to avoid attack vectors like [symlink races](https://capec.mitre.org/data/definitions/27.html).

Data::Printer 1.00 (to be released real soon, you should check 0.99_22 which [just hit CPAN](https://metacpan.org/pod/release/GARU/Data-Printer-0.99_022/lib/Data/Printer.pm)), should fix your issue. It no longer evals code so it lets you have symlinks and lax file permissions (unless you have inline filters).

Hope this helps! Please let us know what you think!

**Comment by barefootcoder** [comment]
Admittedly that does shut the warning up.  I can't see any evidence that it's actually paying any attention to the config file tho ... :-/ 

Also, I can't say that I care much for the new colors.  Is there a way to use the config file, assuming it's working, to return to the old color scheme?

**Comment by garu** [comment]
Absolutely! Just add `theme = Classic` to your .dataprinter file and it should do the trick.

**Comment by barefootcoder** [comment]
Okay, I got it working.  The problem appears to be that the old version of the config used `color`, while the new one uses `colors`.  You may want to update the convert code to fix that when it converts.  So, old:
```
{
    color   =>  {
                    number => 'cyan',
                },
};
```
needs to create new:
```
colors.number = cyan
```

**Comment by garu** [comment]
That's a bug! Thank you, I'll make sure it's fixed on the next release.

**Comment by barefootcoder** [comment]
:+1:
