### ISSUE TITLE
Bug: DDP not showing array ranges correctly

### ISSUE THREAD

**Issue by hhg7** [garu/Data-Printer#152]
I have an array like this:
```
    [19] 2109,
    [20] 177,
    [21] 0.836245,
    [22] 1.000000,
    [23] 1.000000,
    [24] 1.000000,
    [25] 1.000000
]
```
this prints correctly when I call DDP like `p @array`

However, when I print an array slice/range or whatever the correct phrase is, like `p @array[20..25]` DDP only prints the last element (I think).  Perhaps I'm doing something wrong, but otherwise I think that this is a bug.

**Comment by garu** [comment]
Hi! Thank you for using Data::Printer and for taking the time to submit this issue.

What you are experiencing is unfortunately a side-effect of Perl's prototypes and array slices. For some reason, `sub p (@)` takes array slices  just fine but `sub p (\[@])` does not. They should - at least in my opinion - behave the exact same way, the only difference being that the \[...] is used for grouping with other kinds of variables. Unfortunately, this happens:

```perl
perl -E 'sub p (@) { say 42 } my @x = (1..10); p @x[3..5]'
42
```

```perl
perl -E 'sub p (\[@]) { say 42 } my @x = (1..10); p @x[3..5]'
Type of arg 1 to main::p must be one of [@] (not array slice) at -e line 1, at EOF
```

Afaik, this is something that's going on ever since prototypes were first implemented, it is quite unlikely this behavior will change, even if we file it as a bug in perl. Too much code in the wild might be relying on this. It also relates to the fact that Data::Printer uses protypes to expect a reference (to an array, in this case), and you can't reference a slice, you can either reference a copy of the slice or reference the entire array and take a slice of references out of that. But I digress.

The solution is to turn your slice into a full-fledged array, either by:

```perl
my @x = @array[20..25]; p @x;  # works!
```

or by wrapping your slice on [...]->@* or @{[]}, like so:

```perl
p [@array[20..25]]->@*;   # works too!
p @{[@array[20..25]]};  # also works!
```

I'll make sure to add a note regarding this on the documentation. Thanks again for reporting!

**Comment by garu** [comment]
Documentation updated adding Array/Hash Slices as a Caveat. Thank you!
