### ISSUE TITLE
Config format conversion help message incorrect

### ISSUE THREAD

**Issue by abraxxa** [garu/Data-Printer#157]
The mesage I just came across was:

```
[Data::Printer] error reading rc file '/home/ahartmai/.dataprinter': syntax error at line 1: { at /home/ahartmai/.plenv/versions/5.32.0/lib/perl5/site_perl/5.32.0/Net/CLI/Interact/Role/Engine.pm line 49.
[Data::Printer] RC file format changed in 1.00. Usually all it takes is:
cp /home/ahartmai/.dataprinter /home/ahartmai/.dataprinter.old && perl -MData::Printer::Config -E 'say Data::Printer::Config::convert(q(/home/ahartmai/.dataprinter))' > /home/ahartmai/.dataprinter
Please visit https://metacpan.org/pod/Data::Printer::Config for details. at /home/ahartmai/.plenv/versions/5.32.0/lib/perl5/site_perl/5.32.0/Net/CLI/Interact/Role/Engine.pm line 49.
```

The error is in the filename  `.dataprinter` of the convert call which should read  `.dataprinter.old`.

**Comment by garu** [comment]
Hi @abraxxa! Thank you for using Data::Printer and for taking the time to submit this issue.

The idea is:
1. create a backup of the original file and name it `.dataprinter.old`;
2. convert the `.dataprinter` file.

If something goes wrong you still have the original in .dataprinter.old

Did I get it wrong? It looks to me as this is what the message is telling people to do, but since I wrote it I might be blind to a typo. Or maybe there's a better way to say what I mean?

I'd really appreciate your input on this one, if you can.

Thanks!

**Comment by abraxxa** [comment]
The code printed works when you pass it the .dataprinter.old file, but not .dataprinter which doesn‘t exist any more after renaming it to .dataprinter.old

**Comment by garu** [comment]
I was able to reproduce the issue and it looks like the conversion gets confused when reading and writing to the same file at the same time. I've changed the code to use `.old` as you suggested. Version 1.0.3 is out and you name is in the credits.

Thank you!
