### ISSUE TITLE
please tag release 1.1.0

### ISSUE THREAD

**Issue by jonassmedegaard** [garu/Data-Printer#173]
It seems the newest release 1.1.0 at CPAN is newer than what exists here on Github.

Please (push latest changes, and) tag latest release here, to ease tracking source corresponding with CPAN releases.

Thanks for a great library!

**Comment by garu** [comment]
Hi Jonas! Thanks for the reminder, v1.1.0 is up on Github.

I'm curious, do you have a particular need/use case for tracking the repo-cpan releases? I ask because I mostly did it for my own sanity, I don't recall anyone particularly interested in it until now.

Cheers! And thank you for using Data::Printer!

**Comment by jonassmedegaard** [comment]
I (re)distribute your project for Debian, where I prefer to have not only released CPAN code but also the underlying git commits, in case I need to investigate a problem and e.g. revert an upstream change or cherry-pick a not-yet-released commit.

https://salsa.debian.org/perl-team/modules/packages/libdata-printer-perl/-/network/debian%2Flatest

**Comment by jonassmedegaard** [comment]
...and for my use of Data::Printer: I find it quite neat for debugging code that I write - e.g. [licensecheck](http://metacpan.org/App-Licensecheck) - by simply loading `DDP`and then `p` an object or variable troubling me.

**Comment by garu** [comment]
That's awesome! Thanks!
