### ISSUE TITLE
Create underlying (but not private) object for other modules to use

### ISSUE THREAD

**Issue by frioux** [garu/Data-Printer#46]
This is an attempt to fix https://rt.cpan.org/Ticket/Display.html?id=84103 .

My plan is to extract the core of Data::Printer into an object where you call methods on said object to print things.  All configuration of the object will unsurprisingly be attributes on the (Moo based) object.  If you would like me to implement it another way please comment :)

The first step after that will be to use a single global object for all exports, just to get going.  After that we can have an object per package importing into, optionally.  Finally, I'd recommend converting the importer to Sub::Exporter as the current alias functionality is also global.

**Comment by jayallen** [comment]
I just ran into a problem with what I believe to be the exact same cause: My `rc_file`-set properties kept reverting (or, as I found out, are getting overwritten).  It seems that the package-scoped $Data::Printer::properties hashref is overwritten in the `Data::Printer::import()` anytime a new package subsequently uses Data::Printer with `$args`.  Am I correct that this is a similar issue (or the same one) with same root cause?

**Comment by garu** [comment]
Hi everyone! Sorry for the (super) long wait. The first 0.99 trials have hit CPAN with the fix, and Data::Printer::Object is documented and available for use. I'm still tweaking some missing bits&bugs but please test if you can, othewise this is what Data::Printer 1.0 will look like pretty soon!

Thanks again for the support <3
