### ISSUE TITLE
Last release is from 2012 , last commit is from Dec 2014

### ISSUE THREAD

**Issue by Flimm** [garu/Data-Printer#57]
I'm not trying to nag you, it's just that I like to check that modules are actively maintained before bothering to contribute patches. This one seems to be maintained on GitHub but not on CPAN?

**Comment by garu** [comment]
Hello! Thanks for your interest in Data::Printer :)

Actually, the last release was on Dec 2014 as well: https://metacpan.org/pod/release/GARU/Data-Printer-0.35_01/lib/Data/Printer.pm

It's a developer release, because of some outstanding changes that will happen to the default settings, namely https://github.com/garu/Data-Printer/issues/16. Due to Data::Printer's popularity, I want to make some more noise regarding the problem and the fix, so more people are aware of it and able to fix their code (if it needs fixing). So feel free to comment on that issue and spread the word - a stable release is bound to reach CPAN in early february.

Cheers!
