### ISSUE TITLE
What do you think about using SemVer for version Data::Printer number?

### ISSUE THREAD

**Issue by bessarabov** [garu/Data-Printer#65]
http://semver.org/ 

I know that this is not the standard way to version libraries in Perl, but Semver is a great standard and It makes backwards-incompatible changes easier.

**Comment by garu** [comment]
I don't know, mate. I mean, SemVer is indeed a great standard, and if it really allowed us to make back-incompat changes without worrying, I'd change all my modules to it in a heartbeat.

But making backwards-incompatible changes is never easy because CPAN tools don't let us set an API version (which could be interpreted as the first digit of SemVer), so no matter what your version number is, if someone installs a dist (`perl Makefile.PL` & friends, either manually of via cpan[mp]) it will install the latest version and, if it's not back-compat, it *will* break other people's code anyway :(

In a "glass half full" kind of way, I like to think of this as a feature, forcing developers to think thrice before breaking back-compat, and trying their best to design APIs that are future-proof - a daunting task, sure, but what's the fun of coding without a little challenge ;)

Finally, I think there are a lot of magic (and thus potential issues) involved with numbers that aren't numbers (i.e. two dots) in Perl 5 so, unless there's a really compelling reason not to, maybe [version numbers should be boring](http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/) :)

What do you think? Other than making it easier for a human who understands SemVer to look at the version and think "maybe we shouldn't upgrade to this one just yet", is there another real benefit for SemVer in a Perl 5 environment? Or should this benefit be enough to warrant a change to SemVer, even considering the ?

**Comment by oalders** [comment]
I like semver, but once the module is in the wild, I think the ship has sailed on changing the versioning scheme. "Recommendation: don't switch version number schemes for a published module" See http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/

**Comment by bessarabov** [comment]
This is marked as 'recommendation'. I think that SemVer is worth changing versioning scheme.
 
The current version for Data::Printer is 0.36. From SemVer point of view it can be interprited that this library is in initial development stage. Here is the quote from http://semver.org/ :

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

From my point of view. it is ok to release `1.0.0` version now.

The text http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/ states :

> For the most part, version numbers are used to answer just two questions:
>    What version of Module X does Module Y require in order to work properly?
>    Is there a more up-to-date release of Module Z available?

SemVers gives the answer for one more question that is important: "Can I just upgrade to that version or should I change my code to make upgrade possible?"

I have switched all my perl modules to SemVer (https://metacpan.org/author/BESSARABV) and I'm pretty happy with it.

The downside of SemVer is that it is not common in Perl world. I don't know any popular Perl library that uses that scheme, but I think that SemVer is worth using — it is standard, it is simple and it is popular.

**Comment by oalders** [comment]
Right, if you moved from something like `0.36` to `1.000000` then there shouldn't be any issue with sorting the old and new version numbers.

**Comment by jayallen** [comment]
+1 for SemVer.  I use it for everything I create.

**Comment by enriqueiglesias** [comment]
I like semver, but once the module is in the wild, I think the ship has sailed on changing the versioning scheme. "Recommendation: don't switch version number schemes for a published module for the help regarding printer do visit https://printertechsupportnumbers.com/blog/how-to-fix-epson-error-code-0x97/

**Comment by garu** [comment]
Hey everyone! I am super happy to say Data::Printer 1.0 is released! Or should I say 1.0.0? 😁 

I think you all raised pretty valid points regarding SemVer, so I decided to adopt it for 1.0 onwards.

Thank you so much for raising the issue and chipping in. And thank you for using Data::Printer ❤️
