### ISSUE TITLE
Alias for p_without_prototypes

### ISSUE THREAD

**Issue by hakonhagland** [garu/Data-Printer#87]
When debugging programs, I often tend to mix the standard _"print a variable's value"_ `p $var` with simple
messages to `STDOUT`, like `say "Hello"` or something similar. However, I would like to replace the latter
`say "Hello"` with `p "Hello"` in order to get `Data::Printer`'s `caller_info` attached to the string `"Hello"`. (Other reasons could be consistency and that it is 2 character less to type). The problem is that `p $var`, uses prototypes, whereas `p "Hello"` would require not using prototypes. This means I cannot mix `p $var` with `p "Hello"` in a simple manner. The last call must be written: 
- `Data::Printer::p_without_prototypes "Hello"`, or
- `p ${ \"Hello" }`,

(Note: `p ("Hello", use_protypes => 0 )` does not work. ) Neither of these alternatives seems optimal to me compared to the simple `p "Hello"`. 

Possible solutions:
- Let `Data::Printer::import()` export `p_without_prototypes` as `pwp` or `pp`, or
- Add a configuration option `alias_p_no_prototypes` that can be set in the configuration file.

The first option is probably not good as it is not backwards compatible (it could pollute the callers namespace whithout the caller's knowledge and something could in theory break)..

The last option seems viable though: The user simply puts the following into his `.dataprinter` configuration file: `alias_p_no_prototypes => 'pp'`, and then `Data::Printer::import()` will import the alias `pp` into the callers namespace.

I created a [pull request](https://github.com/garu/Data-Printer/pull/86)

What do you think?

**Comment by bessarabov** [comment]
There is also one more possible solution. You can write in you `~/.dataprinter`:

```
{
    use_prototypes => 0,
}
```

This will allow `p $var` and `p 'Hello'` and it will work. But you need to write `p \@arr;` with such setting.

**Comment by hakonhagland** [comment]
Yes, that is true.. forgot about that.. I am kind of used to having `p` work with `use_prototypes => 1` (I did not like having to type that extra backslash in front of every hash and array so I never considered `use_prototypes => 0`). However, I can see that my suggestion would imply typing `pp "Hello"` instead of simply `p "Hello"` ( when `use_prototypes => 0` ). Now, that is one character saved, but now I have to add a backslash in front of each hash and array.  I still think typing `pp` would be simpler to type on the keyboard than `\%`.. ( of course what option one would prefer would depend on habits, and on how often one printed a hash or array compared to a string, and so on ). So, I still think this option could be considered as it would give the user more freedom to choose the option that suits him.

**Comment by garu** [comment]
Hi @hakonhagland! Like @bessarabov suggested, removing the prototype on the .dataprinter file should work. But like you said it creates another set of issues - I also dislike having to add the "\\" before variables, which is why I used prototypes in the first place :)

But fear not! This is what I usually do:

```perl
    p @var, as => "Hello";
```

*as => XXX* is a shortcut for *"caller_info => 1, caller_message => XXX"*. It will prepend your message before the var. If you just want to output some string to STDERR (i.e. without any variable output), the best way is still to just do:

```perl
    warn "Hello";
```

It's 3 more characters than "p" but it will do the exact same thing (unless of course you're outputting DDP to a handle or something other than STDERR)

I'm going to close this issue for now but (and I really mean this), if you feel this is a shortcoming of DDP let's keep the conversation going! Because I want it to be as helpful as possible while still maintaining its core purpose of printing data in a human-friendly way!

For example, a while ago someone asked me to create a function on DDP that would behave just like Data::Dumper's `Dumper()`, meaning something (let's call it `dd`) which would do:

```perl
    dd "Hello";    # prints Hello
    dd $foo, $bar; # prints the content of $foo and $bar as if they were a list of 2 values.
    dd @var;       # prints the content of @var as a list
    dd %var;       # prints the content of %var as a list (not as a hash because we can't tell)
```

and so on. It would not take any extra arguments and consider every input as something to dump. I've considered it but dismissed because I wouldn't want to pollute the caller's namespace yet again, so you would have to call it as `DDP::dd "Hello"`.

Would this help you? Do you think this is something we want to do, or is it overkill?

Thanks!
