### ISSUE TITLE
Data::Printer always "autovivifiies" hash keys ?

### ISSUE THREAD

**Issue by grtodd** [garu/Data-Printer#92]
I can't see an option that would control this.

Here `$h{"one"}` gets created with an `undef` value:

```
% perl -MDDP -E '%h = () ; p $h{"one"}; p %h;'
undef
{
    one   undef
}
```

The behaviour with `Data:::Dumper` is different:

```
% perl -MData::Dumper -E '%h = () ; print Dumper $h{"one"}; print Dumper \%h;'
$VAR1 = undef;
$VAR1 = {};

```

**Comment by bessarabov** [comment]
I'm not sure that this answers your question, but in case you use DDP without prototypes it works as Data::Dumper:

```
bessarabov@5:~$ perl -E 'use DDP; %h = (); p $h{"one"}; p %h;'
undef
{
    one   undef
}
bessarabov@5:~$ perl -E 'use DDP { use_prototypes => 0 }; %h = (); p $h{"one"}; p %h;'
undef
undef
bessarabov@5:~$
```

**Comment by garu** [comment]
Hi @grtodd! This is yet another unfortunate side-effect of using prototypes. The way they work, to allow people to provide a single argument to `p()` and `np()`, we must use backslashed prototypes (`\$`) and start with a reference to your variable - this way we don't have to care whether the developer did `p(@foo)`, `p($foo)`, `p(%foo)`, etc. This means when you wrote:

```perl
p $h{"one"}
```

You were actually sending us `\$h{"one"}`, which unfortunately will always create the key. You can check that behaviour yourself by running:

```perl
perl -E '\$x{bla}; say keys %x'
```

I went to p5p and they said it is expected behavior on some left hand side. Below are the relevant bits of that discussion:

```
< Zefram> couldn't do much else.  without the hash element being created, what would the reference returned by \ be referring to?
< TonyC> maybe a PVLV, but changing it might be a back-compat issue
< TonyC> garu: what you're seeing isn't autovivication - that refers to initializing an undef variable as a reference when you use it as one
< Zefram> fundamentally, \ is treating its operand as an lvalue, same as if it were on the lhs of an assignment
< Zefram> it's not well documented which operations will eagerly create the hash element like that.  foo($x{bla}) *also* treats $x{bla} as an lvalue, but doesn't eagerly create it.  it
                passes a PVLV to foo(), which can then create the hash element by assigning to $_[0]
< Zefram> this is a hedge because function arguments are usually taken by value but there's no type information to say which arguments specifically are taken by reference and so need the lvalue treatment
< garu> I see. Is there any consistency?
< garu> and, if not, should we consider forcing one? Even if, as TonyC mentioned, it might create back-compat issues?
< Zefram> it's consistent between perl versions, and is so long standing that it would be very troublesome to change
< Zefram> making all lvalue contexts behave the same would probably not be worthwhile
```

So it's as @bessarabov said. The only way to prevent this is to not use prototypes at all 😕  You can achieve that by several ways, my favourite being adding "use_prototypes => 0" on your [`.dataprinter`](https://metacpan.org/pod/Data::Printer#CONFIGURATION-FILE-RUN-CONTROL) file and forgetting about it.

**Comment by grtodd** [comment]
OK thanks and to @bessarabov  as well.  This great explanation could appear in the POD :-)
